### ISSUE TITLE
[FEAT] 카카오톡 로그인 구현과 관련 서버 연결

### ISSUE THREAD

**Issue by mini-min** [TeamNADA/NADA-iOS-ForRelease#101]
# 👀 이슈 (issue)

카카오톡 소셜 로그인 로직을 추가하겠습니다.

# 🚀 to-do

- [x] Kakao Developers 애플리케이션 등록
- [x] AppDelegate 카카오 SDK 초기화 코드 추가
- [x] 카카오톡 설치 여부에 따른 카카오톡 연결 코드 분리
- [ ] 토큰 유무에 따른 시작화면 변경
- [x] 사용자 정보 가져오는 메서드
- [x] jwt 토큰 처리
- [x] 더보기 뷰, 회원탈퇴 메서드
