### ISSUE TITLE
[FEAT] 스플래시 뷰 구현, 탭바 수정 자잘한 작업 진행

### ISSUE THREAD

**Issue by mini-min** [TeamNADA/NADA-iOS-ForRelease#114]
# 👀 이슈 (issue)

스플래시 뷰를 구현하고, 하단에 들어가는 공통 탭바 구분선을 수정하겠습니다.

# 🚀 to-do

- [x] 스플래시 뷰 구현 -> 다크 모드 대응...?
- [x] 스플래시 뷰컨, 스보 모두 Const 등록해두기
- [x] 탭바 구분선 추가
- [x] 탭바 스크롤 시 쉐도우에 대해서는 이야기 먼저한 후 진행 -> 일단 샘플 버전 제작
