### ISSUE TITLE
[FEAT] 더보기 뷰 추가 작업

### ISSUE THREAD

**Issue by mini-min** [TeamNADA/NADA-iOS-ForRelease#135]
# 👀 이슈 (issue)

더보기 뷰에서 필요한 디테일한 작업을 시작합니다.

# 🚀 to-do

- [x] 개인정보 처리방침, 서비스 이용약관 노션 링크와 연결
- [x] Team NADA 뷰 구현과 연결
- [x] 오픈소스 라이브러리 뷰 구현과 연결
- [x] "로그아웃" 카카오 로직 추가
- [x] "받은 명함 초기화" 서버 연결 + API 추가
- [x] 회원탈퇴 서버 연결
