### ISSUE TITLE
[FEAT] 그룹명 변경 기능 구현

### ISSUE THREAD

**Issue by mini-min** [TeamNADA/NADA-iOS-ForRelease#142]
# 👀 이슈 (issue)

그룹명 변경 기능을 구현하겠습니다.

# 🚀 to-do

- [x] 그룹 편집 뷰, cell 라벨 클릭 인식하도록 변경
- [x] 그룹명 변경 바텀시트 추가 -> Const 추가
- [x] 바텀 시트 데이터 전달
- [x] 기타 SwiftLint 워닝 해결
