### ISSUE TITLE
[FIX] 카카오톡 소셜 로그인과 스플래시 뷰 연결, 수정

### ISSUE THREAD

**Issue by mini-min** [TeamNADA/NADA-iOS-ForRelease#144]
# 👀 이슈 (issue)

카카오톡 소셜 로그인과 관련된 여러 코드를 구현, 수정합니다.

# 🚀 to-do

- [x] 카카오톡 어플이 설치되지 않았을 때 웹으로 카카오톡이 열리는 로직 수정
- [x] 스플래시 어플에 붙이기
- [x] 스플래시 상황에서 자동 로그인 처리 로직 추가하기
- [x] 토큰을 UserDefaults로 보내는걸 제대로 수정해야 함
