### ISSUE TITLE
[FEAT] 메인 엠티 뷰, 로그인 뷰, 그룹 뷰 추가 작업

### ISSUE THREAD

**Issue by mini-min** [TeamNADA/NADA-iOS-ForRelease#151]
# 👀 이슈 (issue)

API 문서 수정되는동안, 제가 해야할 디테일한 작업들입니다.

# 🚀 to-do

- [x] 메인 엠티 뷰 제작 -> Const에 등록까먹지 않고 하기
- [x] 그룹 편집 셀 전체 클릭 시, 바텀시트 표출되도록 변경
- [x] 그룹명 변경 바텀시트 바뀐내용대로 수정
- [x] 그룹 추가 시, 4개 이상일 경우 등록 못하도록 로직 변경
- [x] 로그인 뷰 카카오 로그인 이미지 변경해두기
