### ISSUE TITLE
[FIX] 뷰 수정 한번에 처리

### ISSUE THREAD

**Issue by dlwns33** [TeamNADA/NADA-iOS-ForRelease#152]
# 👀 이슈 (issue)

뷰 관련해서 수정사항 한꺼번에 처리하겠습니다!

# 🚀 to-do

- [x] 그룹 선택 바텀시트 수정
- [x] QR스캔 라벨 화이트로 고정
- [x] 명함 상세뷰 네비바 색깔 수정
- [x] 명함 그룹 뷰 맥스 대응
