### ISSUE TITLE
[FIX] 명함생성뷰 버그 해결

### ISSUE THREAD

**Issue by hyun99999** [TeamNADA/NADA-iOS-ForRelease#156]
# 👀 이슈 (issue)

명함생성뷰와 맞짱 한번... 해보겠습니다..
이젠 물러날 수 없다..

# 🚀 to-do

- [x] 배경 선택 셀 셀렉트 풀림
- [x] 명함생성뷰에 `shouldResignOnTouchOutside = true` 추가
- [x] 바텀시트 선택 후 어떤 뷰를 눌러도 바텀시트가 등장
    - 텍필 -> 바텀 하면 키보드가 안꺼짐
- [x] 피커뷰 완료 누르면 프론트카드 체크가 안됨 해결
