### ISSUE TITLE
[FEAT] 명함생성 뷰 텍스트필드 기능 구현

### ISSUE THREAD

**Issue by hyun99999** [TeamNADA/NADA-iOS-ForRelease#18]
# 👀 이슈 (issue)

명함생성 뷰의 필수,선택 정보를 입력받는 텍스트필드 관련 효과를 구현하고자한다.

# 🚀 to-do

- [x] 텍스트필드 입력 시 테두리 색 변경
- [x] 텍스트필드 선택 후 뷰 터치하면 키보드 내리는거 구현
- [x] 텍스트필드 입력 완료 후 키보드 내리는거 구현
- [x] 텍스트필드 선택 후 뷰 올리기(collectionview 에 inset 부여)
- [x] 필수정보 입력 시 "완료" 버튼 활성화
- [x] 전반적인 컬러 에셋 적용
