### ISSUE TITLE
[FEAT] 유저 관련 서버 추가 연결

### ISSUE THREAD

**Issue by mini-min** [TeamNADA/NADA-iOS-ForRelease#180]
# 👀 이슈 (issue)

유저와 관련된 서버 처리 부분을 추가 작업합니다.

# 🚀 to-do

- [x] 토큰 재발급 서버 연결
- [x] 로그아웃 서버 연결
- [x] 회원탈퇴 -> '모든 명함 삭제하기'로 네이밍 변경
- [x] '모든 명함 삭제하기' 알림 창 추가 구현, 뷰 연결도 구현, UserDefaults 처리 구현
- [x] 스플래시 자동 로그인 처리 완료하고 연결까지
- [x] 로그인 뷰는 라이트모드만 작동되도록 정리
