### ISSUE TITLE
[FEAT] 메인, 리스트 서버 연결

### ISSUE THREAD

**Issue by mini-min** [TeamNADA/NADA-iOS-ForRelease#184]
# 👀 이슈 (issue)

메인, 리스트 뷰에서 사용되는 서버를 연결합니다.

# 🚀 to-do

- [x] 메인 서버 불러오기
- [x] 리스트 서버 불러오기
- [x] 리스트 편집 핀 클릭시 완료 서버
- [x] 리스트 편집 드래그시 완료 서버
- [x] 자신의 명함 삭제 서버
- [x] 기타 -> 리스트에서 핀된 명함은 삭제 스와이프가 되지 않도록 로직 변경
