### ISSUE TITLE
[FEAT] 명함 리스트뷰 Alert창 구현

### ISSUE THREAD

**Issue by mini-min** [TeamNADA/NADA-iOS-ForRelease#20]
# 👀 이슈 (issue)

명함 리스트 화면에서 SwipeAction을 했을 때, 삭제를 클릭하면 나오는 Alert 창을 구현하겠습니다.

# 🚀 to-do

- [x] Alert 함수 추가
- [x] 커스텀 디자인을 위한 Extension 추가
- [x] Swipe Action과 연결
