### ISSUE TITLE
[FIX] 명함 그룹 뷰 1차 버그 해결

### ISSUE THREAD

**Issue by dlwns33** [TeamNADA/NADA-iOS-ForRelease#218]
# 👀 이슈 (issue)

그룹뷰에서 카드를 추가하면 애니메이션이 풀리면서 viewWillAppear도 호출이 안되네요!
whyrano,...whyrano...whyrano...

# 🚀 to-do

- [x] 문제점 파악...
- [x] 그룹뷰에서 애니메이션이 풀리지 않도록 하기
- [x] 추가한 뒤 노티 부르기
- [x] 아이디로 명함 추가했을때 없는 아이디 일때도 키보드가 내려가지 않도록 하기
- [x] CardView 이미지 비율 수정
- [x] 그룹이 변경되었습니다. 알러트
- [x] 그룹 추가 후 붙어버리는 이슈
- [x] 명함 상세 아이디 없애기

**Comment by hyun99999** [comment]
이것도 QR 스캔에서와 동일하게 overFullScreen 혹은 overCurrentContext 일텐데 뒤에 presentingViewController 가 살아있어서 호출되지 않을거에여! 무슨 문제인지 몰라서 일단 언급만 해드립니다!
