### ISSUE TITLE
[REFACTOR] initializer 메서드 컨밴션에 맞춰 네이밍 변경 및 cell 리펙토링

### ISSUE THREAD

**Issue by hyun99999** [TeamNADA/NADA-iOS-ForRelease#22]
# 👀 이슈 (issue)

- initializer 메서드의 경우 메서드명 prefix 를 'init' 으로 수정
- cell 안에서 nib() 메서드로 nib 객체 생성
- Xib 구조체 만들어서 storyboard 와 view controller 처럼 적용

# 🚀 to-do

- [x] 메서드명 prefix 를 'init' 으로 수정
- [x] 셀마다 nib() 메서드 생성
- [x] Xib 구조체 만들어서 상수로 identifier 다룸
