### ISSUE TITLE
[FEAT] QR 생성, QR스캔 서버

### ISSUE THREAD

**Issue by dlwns33** [TeamNADA/NADA-iOS-ForRelease#223]
# 👀 이슈 (issue)

 QR 생성, QR스캔 서버를 붙여보겠습니다

# 🚀 to-do

- [x] QR 생성할때 앞에 특정 prefix(ex: NADA) 붙이기
- [x] QR 생성후 이미지로 만들고 공유하기 뷰에 넣기
- [x] QR스캔 후 명함 검색 서버 붙이기
- [x] 추가서버까지!
