### ISSUE TITLE
[FEAT] 그룹 편집 뷰 서버 연결

### ISSUE THREAD

**Issue by mini-min** [TeamNADA/NADA-iOS-ForRelease#224]
# 👀 이슈 (issue)

그룹 편집뷰에 들어가는 서버를 연결합니다.

# 🚀 to-do

- [x] 그룹 조회 데이터 서버 연결
- [x] 그룹 삭제 서버 연결
- [x] 그룹명 변경 서버 연결
- [x] 그룹 추가 서버 연결
