### ISSUE TITLE
[FIX] 자동 로그인 버그 해결

### ISSUE THREAD

**Issue by mini-min** [TeamNADA/NADA-iOS-ForRelease#246]
# 👀 이슈 (issue)

자동 로그인과 관련된 버그를 해결하겠습니다.

# 🚀 to-do

- [x] 카카오톡에서 '연결끊기'시, 처리 로직 추가(AppDelegate)
- [x] Apple에서 '연결끊기'시, 처리 로직 추가(AppDelegate)
- [x] 스플래시에서 토큰 처리 로직 수정
- [x] 루트 뷰컨을 수정해서 화면전환이 팍되는 문제 해결
