### ISSUE TITLE
[FIX] 그룹 편집 버그 해결과 알림창 추가

### ISSUE THREAD

**Issue by mini-min** [TeamNADA/NADA-iOS-ForRelease#260]
# 👀 이슈 (issue)

그룹 추가, 편집뷰 버그 해결합니다.

# 🚀 to-do

- [x] 그룹 추가시, 그룹에 바로 업데이트 되지 않는 이슈 해결
- [x] 그룹 편집시, 그룹에 바로 업데이트 되지 않는 이슈 해결
- [x] 그룹 삭제시, 그룹에 바로 업데이트 되지 않는 이슈 해결
- [x] 그룹 추가된 다음 알림창 표출
