### ISSUE TITLE
[ADD] 라이트 모드 방지, Pods 폴더 제거, 앱이름 변경

### ISSUE THREAD

**Issue by hyun99999** [TeamNADA/NADA-iOS-ForRelease#28]
# 👀 이슈 (issue)

- 라이트 모드를 막아서 상태바의 색을 하얀색으로 고정
- .gitignore 파일 수정해서 Pods 폴더가 올라가지 않도록 함
- 앱 이름 NADA 로 변경

# 🚀 to-do

- [x] 라이트모드 막기 - 현규
- [x] Pods 폴더 지우기 - 현규
- [x] NADA 이름 바꾸기 - 현규
