### ISSUE TITLE
[Fix] 액세스 토큰 만료 시 갱신 성공 후, 무한로딩 버그 해결

### ISSUE THREAD

**Issue by hyun99999** [TeamNADA/NADA-iOS-ForRelease#328]
# 👀 이슈 (issue)

- 액세스 토큰 만료 시 갱신 후, 아무런 동작을 정해주지 않았다.
- 액세스 토큰 만료, 리프레시 토큰이 유효할때 무한로딩에 빠짐

# 🚀 to-do

- [ ] 액세스 토큰 만료 시 갱신 후, 재요청해야할 것 같다.
- [x] 시나리오 작성이 필요해보임.
- [ ] `스플래시 -> 홈(AT, RT 만료시) -> 로그인뷰` 는 구현해둠
- [ ] `스플래시 -> 홈(AT 만료) -> plugin 에서 AT, RT 갱신 -> ??

**Comment by hyun99999** [comment]
서버 API 들이 변경되면서 새로운 정책을 통해서 구현 예정
