### ISSUE TITLE
feat: 앱내에서 동적링크 생성

### ISSUE THREAD

**Issue by hyun99999** [TeamNADA/NADA-iOS-ForRelease#338]
# 👀 이슈 (issue)

- 앱내에서 동적링크를 생성해서 명함을 공유할 때 큐알코드 메시지로 생성하기

# 🚀 to-do

- [x] firebase 프레임워크를 사용하여 동적링크생성
- [x] 큐알코드 메시지 수정
- [x] 큐알코드 인식하는 곳에서 달라진 prefix 수정하기

**Comment by hyun99999** [comment]
#334 이슈도 동일하게 진행
