### ISSUE TITLE
[CHORE] 컬러 익스텐션 수정

### ISSUE THREAD

**Issue by mini-min** [TeamNADA/NADA-iOS-ForRelease#34]
# 👀 이슈 (issue)

태양이가 이름 바꿔주는대로 컬러 익스텐션을 수정하겟습니다.

# 🚀 to-do

- [x] UIColor 익스텐션 형태 변경
- [x] 컬러 이름 수정
- [x] 기존 컬러 파일 삭제
