### ISSUE TITLE
feat: 동적 링크를 통해 앱 열면 명함 상세뷰 보여주기

### ISSUE THREAD

**Issue by hyun99999** [TeamNADA/NADA-iOS-ForRelease#342]
# 👀 이슈 (issue)

- ~현재, associated domain 을 추가했는데도 동적 링크를 통해서 앱일 열리지 않고, 앱스토어로 가고 있습니다. 동적 링크를 앱 내에서 잘못 생성하고 있는 것 같습니다.~
    - Firebase 에서 iOS 앱을 추가할 때, 팀 ID 를 비워둬서 작동하지 않았었습니다. 해결했습니다.
- ~이를 해결하여 앱을 열 수 있도록 수정하겠습니다.~
- 추가로, 앱을 열었을 때 ~명함 조회 바텀 시트를 보여줄 수 있도록 하겠습니다.~
- 플로우를 헷갈렸는데 명함이 추가되고, 해당 명함의 명함 상세뷰가 홈에 등장하게됩니다.

# 🚀 to-do

- [x] 동적 링크 수정하여 앱 설치시 앱을 열 수 있도록 구현.
- [x] 앱을 열었을 때 명함 상세뷰 보여주기
- [x] 로그인 유무를 판단해서 로그인된 경우에 명함 추가
