### ISSUE TITLE
fix: 기본 명함 생성 뷰 수정

### ISSUE THREAD

**Issue by hyun99999** [TeamNADA/NADA-iOS-ForRelease#351]
# 👀 이슈 (issue)

- 기본 명함 생성 뷰 수정
<img width="311" alt="스크린샷 2023-01-30 오후 5 50 34" src="https://user-images.githubusercontent.com/69136340/215433942-05c48d00-daa1-4ab8-9978-71ac44db1f47.png">

# 🚀 to-do

- [x] 생년월일 플레이스 홀더 변경 -> "생일"
- [x] 추가 정보 순서 변경
- [x] 추가 정보로 전화번호 입력
