### ISSUE TITLE
[FEAT] 커스텀 탭바 구현

### ISSUE THREAD

**Issue by mini-min** [TeamNADA/NADA-iOS-ForRelease#36]
# 👀 이슈 (issue)

나다 메인 화면에 들어가는 커스텀 탭바를 추가하겠습니다.

# 🚀 to-do

- [x] 탭바 커스텀 디자인
- [x] 탭바 AutoLayout
- [x] 탭바 아이템 이미지 추가
- [x] 포인터 이동 기능 추가
- [x] 뷰컨 연결
- [x] 탭바 gradient, 투명도 추가
