### ISSUE TITLE
feat: 내 명함 목록을 선택할 수 있는 Configurable Widget 추가

### ISSUE THREAD

**Issue by hyun99999** [TeamNADA/NADA-iOS-ForRelease#366]
# 👀 이슈 (issue)
- 위젯 편집을 통해 내 명함 목록을 선택할 수 있는 Configurable Widget 으로 생성.
- cardID 로 명함을 구분해서 선택하도록 설정.
- 데이터 모델의 전역 변수로 목록을 구성.
    - 후에 서버 혹은 로컬 디비로 목록을 구성할 예정

# 🚀 to-do
(#364) 에서 진행함
- [x] Configurable Widget 을 위한 intent definition file 생성 
- [x] 동적 목록으로 설정
---
- [x] 내 명함을 조회할 수 있도록 위젯 뷰 구현
- [x] Provider 구현
