### ISSUE TITLE
fix: 명함 조회 API 수정

### ISSUE THREAD

**Issue by hyun99999** [TeamNADA/NADA-iOS-ForRelease#384]
# 👀 이슈 (issue)

api 문서가 변경됨에 따른 수정

# 🚀 to-do

- [x] 명함 페이지네이션 적용
- [x] 명함 전체 조회 API 반영(페이지네이션 사용x)
- [x] 수정된 API 반영(Card 데이터 모델은 #395 에서 진행)
- [ ]
