### ISSUE TITLE
feat: 취향 조회 API 구현

### ISSUE THREAD

**Issue by hyun99999** [TeamNADA/NADA-iOS-ForRelease#385]
# 👀 이슈 (issue)

명함을 생성할 때 server driven 으로 밸런스게임을 하기 위한 API 구현

# 🚀 to-do

- [x] `cardType` : BASIC / COMPANY / FAN 으로 명함 종류 설정해서 취향을 응답 받아서 명함 뒷면을 구성.
- [x] Taste 데이터 모델 생성
- [x] CardAPI, CardService 수정
- [x] #393
