### ISSUE TITLE
fix: 엠티뷰 수정

### ISSUE THREAD

**Issue by hyun99999** [TeamNADA/NADA-iOS-ForRelease#394]
# 👀 이슈 (issue)

<img width="250" alt="스크린샷 2023-03-29 오전 12 27 32" src="https://user-images.githubusercontent.com/69136340/229671112-521862bf-c9a3-4ec1-b84f-b115fd4bf405.png">

# 🚀 to-do

- [x] 기본 명함 생성 뒷면
- [x] 그룹 편집 엠티뷰
- [x] 명함 모음 엠티뷰
- [x] 홈
- [x] 내 근처의 명함 엠티뷰
- [x] 메인 리스트 엠티뷰
