### ISSUE TITLE
feat: 명함 생성 뒷면 기능 확인

### ISSUE THREAD

**Issue by hyun99999** [TeamNADA/NADA-iOS-ForRelease#396]
# 👀 이슈 (issue)

- #395 PR 이 서버 API 완성 이전에 이루어졌기 때문에 정확한 시나리오 테스트와 결과에 대한 UI 를 보지 못했습니다. 그래서 이 이슈에서 진행하려고 합니다.
- 명함 생성 뒷면에서 UITextView 를 사용해서 TMI 를 입력받고 있는데 이때 여러 시나리오에서 정상 작동하는지, 총 몇자까지 쓸 수 있는지 그래서 제한두는 기능 추가까지 고려하고 있습니다.

# 🚀 to-do

- [x] tmi 입력 중에 화면 터치시 키보드가 내려가는지
- [x] tmi 입력 전과 후 글자의 색상 변화 확인. 테두리 굵기 확인 및 색상 확인
- [x] tmi 최대 몇글자까지 입력가능한지 확인 후, 최대 글자 수 넘으면 삭제 기능 구현
- [x] 명함 뒷면 취향 선택 정상 작동 확인
- [x] 명함 미리보기 정상 작동 확인
- [x] 명함 생성 정상 작동 확인
- [x] 명함 배경 미리보기로 넘기기
- [x] 취향 라벨 여백 확인하기. 현재 안맞음
    <img width="200" alt="스크린샷 2023-04-14 오후 4 37 51" src="https://user-images.githubusercontent.com/69136340/231976648-ff6e947c-f37e-475f-bc5d-e1704856c507.png">
- [x] 명함 미리보기에서 둥글기가 다름
    <img src="https://user-images.githubusercontent.com/69136340/231983785-55d58f4d-afbc-488f-989b-b545d02319fd.jpg" width ="150">
- [x] 이미지 업로드 확인
