### ISSUE TITLE
[FEAT] 메인화면 Card Flip 기능 구현

### ISSUE THREAD

**Issue by mini-min** [TeamNADA/NADA-iOS-ForRelease#44]
# 👀 이슈 (issue)

메인화면에서 명함을 클릭하면 뒷면으로 전환되는 애니메이션을 추가하겠습니다.

# 🚀 to-do

- [x] Swiftlint - identifier_name 지우고 변수명 수정
- [x] transition 애니메이션 추가
- [x] delegate에 didTapCard 사용한 클릭 기능 구현
- [x] 클릭 시 cell을 변경해주는 로직 추가
