### ISSUE TITLE
fix: 수정된 API 관련 에러사항 해결

### ISSUE THREAD

**Issue by dlwns33** [TeamNADA/NADA-iOS-ForRelease#466]
# 👀 이슈 (issue)

수정된 API 관련 에러사항을 해결하겠습니다.

# 🚀 to-do

- [x] 그룹 내 명함 카드 비율 조정
- [x] 미분류 명함 조회
- [ ] 그룹 삭제 확인
