### ISSUE TITLE
[FEAT] 리스트뷰 세부 기능 추가 및 수정

### ISSUE THREAD

**Issue by mini-min** [TeamNADA/NADA-iOS-ForRelease#47]
# 👀 이슈 (issue)

리스트뷰의 세부적인 내용들을 다듬는 작업을 하겠습니다.

# 🚀 to-do

- [x] 리스트뷰에서는 탭바가 보이지 않도록 수정
- [x] 백 스와이프 제스처로 pop하는 기능 구현
- [x] Drag & Drop으로 cell을 정렬하는 기능 구현
- [x] 테이블뷰 셀 구분선 수정
- [x] 핀 고정시 해당 셀의 배경색이 같이 변하도록 수정
