### ISSUE TITLE
fix: 메인 탭 1차 QA 사항

### ISSUE THREAD

**Issue by dlwns33** [TeamNADA/NADA-iOS-ForRelease#490]
# 👀 이슈 (issue)

메인 탭 1차 QA 사항

# 🚀 to-do

- [x] 기기마다 명함 보내기, 명함 받기 카드 사이의 간격이 달라요!
- [ ] 메인탭에서 명함 보내기, 명함 받기, 내 근처의 명함을 누르면 클릭된 상태로 계속 남아있네여..?
- [ ] 바텀시트 올라왔다 내려갈 때 글자가 겹쳐요 (ID로 받기, QR로 받기)

**Comment by hyun99999** [comment]
바텀시트 이왕 고칠거..이전에 얘기했던 sheetpresentcontroller 사용해보시는것도 좋을듯합디다! 쉽게 개선할 수 있으니깐요
