### ISSUE TITLE
feat: ga 세팅 및 온보딩 트래킹

### ISSUE THREAD

**Issue by hyun99999** [TeamNADA/NADA-iOS-ForRelease#516]
# 👀 이슈 (issue)

ga 세팅 및 온보딩 트래킹

# 🚀 to-do

- [x] GoogleService-Info.plist 추가
- [x] AppDelegate 에 ga configure
- [x] 온보딩 버튼 및 뷰 트래킹
