### ISSUE TITLE
chore: firebase 활용한 동적링크 도메인 및 GoogleService-Info 수정

### ISSUE THREAD

**Issue by hyun99999** [TeamNADA/NADA-iOS-ForRelease#532]
# 👀 이슈 (issue)

firebase 활용한 동적링크 도메인 및 googleservice-info 수정

# 🚀 to-do

- [x] 팀 계정으로 firebase 에 프로젝트 생성
- [x] 동적링크 도메인 변경 반영
- [x] googleservice-info 파일 교체
