### ISSUE TITLE
[FEAT] 로그인, 메인, 리스트 서버통신

### ISSUE THREAD

**Issue by mini-min** [TeamNADA/NADA-iOS-ForRelease#54]
# 👀 이슈 (issue)

로그인, 메인, 리스트 서버통신을 시작합니다.

# 🚀 to-do

- [x] 로그인 서버 작업
- [x] 로그인 서버 통신 확인
- [x] 메인 서버 작업
- [x] 메인 서버 통신 확인
- [x] 리스트 서버 작업
- [x] 리스트 서버 통신 확인
