### ISSUE TITLE
fix: 엠티뷰 문구 수정 및 명함 생성 문구 수정

### ISSUE THREAD

**Issue by hyun99999** [TeamNADA/NADA-iOS-ForRelease#554]
# 👀 이슈 (issue)

엠티뷰 문구 수정 및 명함 생성 문구 수정

# 🚀 to-do

- [x] 명함 생성 문구 수정
- [x] 명함 미리보기 문구 수정
- [x] 내 명함 엠티뷰 문구 수정
- [x] 명함 리스트 엠티뷰 문구 수정
