### ISSUE TITLE
fix: 3차 QA 수정

### ISSUE THREAD

**Issue by dlwns33** [TeamNADA/NADA-iOS-ForRelease#559]
# 👀 이슈 (issue)

이슈에 대해 간략하게 설명해주세요

# 🚀 to-do

- [x] 내 명함이 없고 / 다른 사람 명함과 궁합을 보려고 할 때 버튼만 눌러지고 아무 반응이 없음
- [x] 뭔가 명함 모음 갱신 (?) 이 제대로 안 되고 있는 느낌,,,
- [x] MBTI 다크모드 아이콘으로 변경해 주세용
