### ISSUE TITLE
fix: 4차 QA 수정

### ISSUE THREAD

**Issue by dlwns33** [TeamNADA/NADA-iOS-ForRelease#567]
# 👀 이슈 (issue)

4차 QA 수정

# 🚀 to-do

- [x] 특정 명함에서만.. 궁합이 안 뜨는데 원인을 모르겠습니다..?
- [x] QR…….. 왜 인식이 안되지요…….
- [x] 궁합 점수 int로 변경
