### ISSUE TITLE
feat: 명함 수정을 위한 명함 생성 뷰 설정

### ISSUE THREAD

**Issue by hyun99999** [TeamNADA/NADA-iOS-ForRelease#588]
# 👀 이슈 (issue)

명함 수정을 위한 명함 생성 뷰 설정

# 🚀 to-do

- [x] 명함 생성뷰에 진입할 때 card data model 이 옵셔널이 아니면?
- [x] 혹은, enum 형으로 case 가 수정이라면?
- [x] -> 둘 다 사용하게 됨.
- [x] front/backCardCollectionViewCell 을 만들 때 데이터 모델을 전달.
