### ISSUE TITLE
fix: 그룹명 수정(드래그)

### ISSUE THREAD

**Issue by dlwns33** [TeamNADA/NADA-iOS-ForRelease#591]
# 👀 이슈 (issue)

그룹명 수정을 터치에서 드래그 시 되게 변경

# 🚀 to-do

- [x] 그룹명 수정 드래그 버튼 생성
- [x] 그룹명 수정 터치에서 드래그 시 되게 변경
- [x] 그룹명 수정 터치하면 되던 것 막기
