### ISSUE TITLE
feat: 받은 태그 뷰에서 UISheetPresentationController 적용하여 바텀시트 구현

### ISSUE THREAD

**Issue by hyun99999** [TeamNADA/NADA-iOS-ForRelease#602]
# 👀 이슈 (issue)

- UISheetPresentationController 를 사용할 수 있도록 extension 함수 만들기
- 받은 태그 뷰에서 UISheetPresentationController 적용하여 바텀시트 구현

# 🚀 to-do

- [ ] extension 함수 만들기
- [x] grabber, corner radius, title
- [ ] ~alpha 값도 가능?~
- [x] 받은 태그 뷰 일부 구현(서버 통신을 고려한 작업 전까지)

**Comment by hyun99999** [comment]
구현에 초점을 맞추기 위해서 우선적으로 체크안된 todo list 는 이슈로 전환하겠습니다.
