### ISSUE TITLE
feat: 태그 보내기 뷰 구현

### ISSUE THREAD

**Issue by hyun99999** [TeamNADA/NADA-iOS-ForRelease#616]
# 👀 이슈 (issue)

태그 보내기 뷰 구현

# 🚀 to-do

- [x] UISheetPresentationController 를 사용하여 custom detent 를 통해 구현
- [x] text field 를 활용하여 사용
- [x] 키보드를 통해 서버통신을 위한 동작을 설정
- [x] sendUI() 상태가되면 TextField 사용자 입력 막기
- [ ] editUI -> sendUI 변경 시 custom detent 로 변경
- [ ] Observabl 을 사용하여 변수의 변경에 따른 UI 변경 시도
