### ISSUE TITLE
fix: 2차 메인화면 QA

### ISSUE THREAD

**Issue by dlwns33** [TeamNADA/NADA-iOS-ForRelease#629]
# 👀 이슈 (issue)

2차 메인화면 QA 고쳐보겠습니다.

# 🚀 to-do

- [x] 공지 오른쪽에 구분선이 없는듯한..? 디자인에는 다음 공지 전에 구분선이 있는듯한 느낌이에여! (첨부 이미지 내 1번, 다크모드도 동일해요)
- [x] 명함 만들기 부분에서요! 저 부분 색상이 디자인과 다른듯 한데 색상 확인 부탁드려요! 지금 보니 폰트도 다른 것 같아요 (첨부 이미지 내 2번, 다크모드도 동일해요)
- [ ] 공지 올리니까.. 라벨 내 글자가 센터가 안 맞어요!
- [x] 내 명함 글자만 text_bold_01로 처리해 주세요..!
- [x] 버튼 그림자 없애고 아웃라인 추가해 주세욥 (아웃라인 컬러 이름-button)
- [x] 내명함 만들기 버튼 & 아래 명함보내기, 명함받기 버튼 간격 24
- [x] 테플 다크모드에 > 아이콘이 안 보여요
- [x] 내명함~내근처의 명함 버튼들의 위치가 넘 위쪽으로 쏠려있어요
- [x] 배너 캐러셀 마지막 콘텐츠 좌우 마진이 안 맞아용
