### ISSUE TITLE
[FEAT] 회원관련 추가 서버통신

### ISSUE THREAD

**Issue by mini-min** [TeamNADA/NADA-iOS-ForRelease#63]
# 👀 이슈 (issue)

회원과 관련된 추가 담당 서버통신 작업을 진행하겠습니다.

# 🚀 to-do

- [x] [GET] 소셜 로그인_jwt 서버통신 파일 구현까지만
- [x] [POST] 회원가입 서버통신 구현 & 체크 
- [x] [DELETE] 회원탈퇴 서버통신 구현 & 체크
