### ISSUE TITLE
feat: 태그 보내기 뷰 연결

### ISSUE THREAD

**Issue by hyun99999** [TeamNADA/NADA-iOS-ForRelease#636]
# 👀 이슈 (issue)

명함 상세 뷰에 태그 보내기 뷰 연결

# 🚀 to-do

- [x] cardUUID 뿐만 아니라 cardName 도 가져와서 UI에 보여주기
- [x] 명함 상세 뷰에서 태그 보내기 뷰로 연결
- [x] 받은 명함 뷰 present 원상복구하기(현재 해당 경로로 태그 보내기 뷰를 보여주고 있음)
