### ISSUE TITLE
feat: 명함 상세 스크롤 뷰 수정

### ISSUE THREAD

**Issue by dlwns33** [TeamNADA/NADA-iOS-ForRelease#651]
# 👀 이슈 (issue)

명함 상세 보수공사 진행하도록 하겠습니다

# 🚀 to-do

- [x] 배경색이.. 초록색으로 질려있네요..? 뭔가 구분하려고 그랬던 거 같은..
- [x] 도움말.. 연결이 안 되어있는듯 해요…?
- [ ] 명함 모음에서, 리프레시 했을 때 1. 새로고침이 뜨고 2. 받은 태그 정보를 받아올 수 있도록 되어야 하는데 안 되네여!
- [x] 명함 ID값이 사라졌어요 (이미지 참고)
- [x] 얘 왜 체크가 되죠 (이미지 참고)
- [ ] 명함 모음에서, 명함 상세에 들어가지 않고 링크 부분을 클릭하면 그 링크로 이동이 되더라구요
- [x] 태그가 많을 때 스크롤이 별도로 생기네여?

**Comment by hyun99999** [comment]
화이팅입니다!!
짱짱선배라 다 하시겠지만!! 어려운거 있으면 같이 논의해봐용!
