### ISSUE TITLE
[CHORE] 컬러 이미지 에셋 수정

### ISSUE THREAD

**Issue by mini-min** [TeamNADA/NADA-iOS-ForRelease#66]
# 👀 이슈 (issue)

바뀐 화면에서 사용되는 컬러와 이미지 에셋을 추가하겠습니다. 익스텐션 내용도 바꾸겠습니다.

# 🚀 to-do

- [x] 이미지 에셋 기존 내용 삭제 & 새로운 내용 추가
- [x] 컬러 에셋 새로운 내용으로 수정 (라이트 다크 분리)
- [x] UIColor Extension 수정 -> 제플린에 있는 것 그대로 긁어오기
- [x] 기존 이미지, 컬러 설정해둔 코드 반영해서 수정
- [x] 다크모드 제한 해제
