### ISSUE TITLE
feat: 밸런스 게임 버튼 선택 시 버튼 바뀌도록 구현

### ISSUE THREAD

**Issue by hyun99999** [TeamNADA/NADA-iOS-ForRelease#663]
# 👀 이슈 (issue)

highlighted 될 때 background image 가 바뀌도록 했는데 탭으로 영향을 받지 않았습니다.
그래서 UIButton.Configuration 를 사용해보려고 합니다.

# 🚀 to-do

- [x] 다른 경우에 UIButton.Configuration 을 사용했을 때 정상적으로 적용됨. 
- [x] -> UIButton.Configuration 을 사용했는데 바로 highligted 가 안됨
- [x] 근데! 이게 cell 안에 있는 버튼이라서 이벤트가 한번 거쳐서 가는것 같다는 생각이 듦
