### ISSUE TITLE
[FEAT] 바뀐 레이아웃 수정 작업 

### ISSUE THREAD

**Issue by mini-min** [TeamNADA/NADA-iOS-ForRelease#68]
# 👀 이슈 (issue)

제가 담당하고 있는 뷰들 빠르게 바뀐 화면으로 수정하겠습니다.

# 🚀 to-do

- [x] 로그인 뷰
- [x] 탭바 & 기존 탭바 내용 삭제
- [x] 나다 메인 뷰
- [x] 카드 리스트 뷰
- [x] 카드 뒷면 cell
- [x] 공통 바텀시트 클래스 추가 
- [x] 더보기 뷰 구현, 탭바 컨트롤러 연결 -> 수정 가능성 있음
