### ISSUE TITLE
chore: 앱 버전 3.0.0 업데이트 및 강제 업데이트 정상 작동 확인

### ISSUE THREAD

**Issue by hyun99999** [TeamNADA/NADA-iOS-ForRelease#688]
# 👀 이슈 (issue)

앱 버전 3.0.0 업데이트 및 강제 업데이트 정상 작동 확인

# 🚀 to-do

- [ ] 앱 버전 3.0.0 업데이트
- [ ] 스웨거로 설정해주면 강제 업데이트 정상 작동 확인
- [ ] 앞자리 바뀜에 대응 / 강제 업데이트를 통한 업데이트 이후 업데이트 창 확인
- [ ] 선택이 아닌 강제이기 때문에 `확인했습니다` 버튼은 숨겨진다
