### ISSUE TITLE
[FEAT] 리스트뷰, 더보기뷰, 그룹 편집뷰 세부 구현

### ISSUE THREAD

**Issue by mini-min** [TeamNADA/NADA-iOS-ForRelease#74]
# 👀 이슈 (issue)

리스트뷰, 더보기뷰, 명함 그룹뷰 세부 구현하겠습니다 ^__^

# 🚀 to-do

💡리스트 뷰
- [x] 탭바 안보이게 변경
- [x] 리스트뷰 구분선 수정
- [x] 핀 고정시 위치 수정 불가능하도록 로직 추가
- [x] 핀을 바꾸면, 위치 변경되도록 로직 추가

💡더보기 뷰
- [x] 화면 구현
- [x] Constant 추가

💡그룹 편집뷰
- [x] 화면 구현
- [x] alert창 구현
- [x] 바텀 시트 구현, 연결 (그룹 추가, 그룹명 변경) -> 키보드 표출, 키보드 내용 바꾸기까지
- [x] Constant 추가
