### ISSUE TITLE
[CHORE] 컬러 라이트 모드에 맞춰서 수정

### ISSUE THREAD

**Issue by mini-min** [TeamNADA/NADA-iOS-ForRelease#82]
# 👀 이슈 (issue)

제플린에 따라 컬러를 맞춰주기 위해서 수정합니다.
   
# 🚀 to-do

- [x] Colors Asset 수정
- [x] 컬러 Extension 수정
- [x] 색깔 적용했던 뷰 싹다 수정
