### ISSUE TITLE
[FIX] 명함 그룹 화면 수정

### ISSUE THREAD

**Issue by dlwns33** [TeamNADA/NADA-iOS-ForRelease#87]
# 👀 이슈 (issue)

- 명함 그룹화면으로 들어올때 미분류가 selected되지 않는 이슈
- 그룹 collectionview에서 마지막 셀이 끝까지 보이지 않는 이슈

# 🚀 to-do

- [x] isSelected 코드 변경
- [x] groupCollectionView estimated size 조정
- [x] groupCollecvtionView inset 조정
- [x] 그룹 뷰에 쓰는 cell const로 변경
