### ISSUE TITLE
[FIX] 카드 셀 뒷면 수정 & bottomSheet 수정

### ISSUE THREAD

**Issue by mini-min** [TeamNADA/NADA-iOS-ForRelease#89]
# 👀 이슈 (issue)

카드 셀 뒷면을 수정합니다.

# 🚀 to-do

⭐️카드 뒷면 셀
- [x] BackCardCell, initCell 수정 (bool형으로 받아서, 메서드에서 처리하는 방식)
- [x] 미리보기 뷰 부분 맞춰서 수정
- [x] Bundle 빠져있는 내용들 추가

⭐️바텀시트
- [x] 표출 시간 delay 이슈 해결

⭐️기타
- [x] 더보기 뷰 구분선 색상 수정
- [x] 이준쌤 명함 모음 뷰 명함 글씨 색 -> background에서 .white로 변경
