### ISSUE TITLE
[FEAT] QR스캔 뷰 구현

### ISSUE THREAD

**Issue by dlwns33** [TeamNADA/NADA-iOS-ForRelease#96]
# 👀 이슈 (issue)

QR관련 화면들을 모두 구현해보도록 하겠습니다

# 🚀 to-do

- [x] QR스캔 뷰 만들기
- [x] QR검색 결과 bottomSheet만들기
- [x] QR 검색 후 그룹선택 bottomSheet 만들기
- [ ] bottomSheet가 내려가도 QR스캔이 다시 되도록 만들기
- [x] X 아이콘 수정하기
